PetCare/blueprints/PetCare.py
# -*- coding: utf-8 -*-
from flask import Blueprint, request, session, redirect, url_for, render_template, abort, jsonify
import time
from Daos.Dao import Dao
from Daos.AccountDao import AccountDao
from Daos.PostDao import PostDao
from ImageHandler import ImageHandler
from Entities import Entities
from EmailHandler import EmailHandler

bp = Blueprint('PetCare', __name__)

def init_db():
	AccountDao().init_db()
	PostDao().init_db()

def close_db():
	Dao().close_db()

@bp.route('/', methods=['GET'])
def homepage():
	return render_template('home_page.html')

@bp.route('/register', methods=['GET', 'POST'])
def register():
	if request.method == 'GET':
		return render_template('register.html', error=None)
	accountInfo = Entities.make_account_info(request)
	if not accountInfo:
		return render_template('register.html', error="Required Informaion Missing")
	accountDao = AccountDao()
	isNewAccount = accountDao.add_account(accountInfo)
	if not isNewAccount:
		return render_template('register.html', error="User Account Existed Already")
	EmailHandler.send_authentication(accountInfo['email'], accountInfo['id'], accountInfo['code'])
	return redirect(url_for('PetCare.login'))

@bp.route('/authenticate', methods=['GET'])
def authenticate():
	accountDao = AccountDao()
	isAuthPass = accountDao.authenticate_account(request.args['userId'].rstrip(), request.args['code'])
	if not isAuthPass:
		return render_template('login.html', error="Authentication Failed")
	session['logged_in'] = request.args['userId'].rstrip()
	return redirect(url_for('PetCare.list_posts'))

@bp.route('/login', methods=['GET', 'POST'])
def login():
	if request.method == 'GET':
		return render_template('login.html', error=None)
	accountDao = AccountDao()
	userId = accountDao.check_account_email_password(request.form['email'], request.form['password'])
	if userId is None:
		return render_template('login.html', error="Invalid User Account")
	if not userId:
		return render_template('login.html', error="Wrong Password")
	session['logged_in'] = userId
	return redirect(url_for('PetCare.homepage'))

@bp.route('/logout', methods=['GET'])
def logout():
	session.pop('logged_in', None)
	return redirect(url_for('PetCare.login'))

@bp.route('/profile', methods=['GET'])
def profile():
	if 'login' in request.args and session.get('logged_in') is not None and session.get('logged_in') != request.args['login']:
		session.pop('logged_in', None)
	if session.get('logged_in') is None:
		if 'login' not in request.args:
			return redirect(url_for('PetCare.login')) 
		else:
			return redirect(url_for('PetCare.prompt_login', userId=request.args['login'], targetId=request.args['userId'].rstrip()))
	accountDao = AccountDao()
	postDao = PostDao()
	accountInfo = accountDao.get_account_info(request.args['userId'].rstrip())
	posts = postDao.get_user_posts(request.args['userId'].rstrip())
	postInfos = [Entities.make_post_output(dict(post)) for post in posts]
	myCurrentPostId = accountDao.get_account_post(session['logged_in'].rstrip())
	status = 'UNRELATED' if myCurrentPostId is None else postDao.check_relation(myCurrentPostId, request.args['userId'].rstrip())
	return render_template('profile.html', account=accountInfo, posts=postInfos, status=status)

@bp.route('/list_posts', methods=['GET'])
def list_posts():
	if session.get('logged_in') is None:
		return redirect(url_for('PetCare.login'))
	accountDao = AccountDao()
	reputation = accountDao.get_account_reputation(session['logged_in'].rstrip())		
	postDao = PostDao()
	posts = postDao.list_limited_posts(reputation=reputation, limit=4, offset=0)
	postInfos = [Entities.make_post_output(dict(post)) for post in posts]
	return render_template('list_posts.html', posts=postInfos, fromFilter=False)

@bp.route('/_load_more_posts', methods=['GET'])
def load_more_posts():
	if session.get('logged_in') is None:
		return redirect(url_for('PetCare.login'))
	accountDao = AccountDao()
	reputation = accountDao.get_account_reputation(session['logged_in'].rstrip())
	postDao = PostDao()
	posts = postDao.list_limited_posts(reputation=reputation, limit=4, offset=request.args.get('offset'))
	postInfos = [Entities.make_post_output(dict(post)) for post in posts]
	return jsonify(postInfos)

@bp.route('/filter_posts', methods=['POST'])
def filter_posts():
	if session.get('logged_in') is None:
		return redirect(url_for('PetCare.login'))

	gender_filter = request.form['gender']
	species_filter = request.form['species']
	age_filter = request.form['age']

	start_date = request.form['start_date']
	end_date = request.form['end_date']
	start_date_value = int(time.mktime(time.strptime(start_date, '%Y-%m-%d'))) if len(start_date) > 0 else 0
	end_date_value = int(time.mktime(time.strptime(end_date, '%Y-%m-%d'))) if len(end_date) > 0 else 0

	accountDao = AccountDao()
	reputation = accountDao.get_account_reputation(session['logged_in'])
	postDao = PostDao()
	all_posts = postDao.list_all_posts(reputation=reputation)

	filtered_posts = []
	for post in all_posts:
		if gender_filter != '-1' and int(gender_filter) != post['gender']:
			continue
		if len(species_filter) > 0 and species_filter != post['species']:
			continue
		if age_filter != '-1' and int(age_filter) != post['age']:
			continue
		if len(start_date) > 0 and post['start_date'] < start_date_value:
			continue
		if len(end_date) > 0 and post['end_date'] > end_date_value:
			continue			
		filtered_posts.append(post)

	postInfos = [Entities.make_post_output(dict(post)) for post in filtered_posts]
	return render_template('list_posts.html', posts=postInfos, fromFilter=True)

@bp.route('/create_post', methods=['GET', 'POST'])
def create_post():
	if session.get('logged_in') is None:
		return redirect(url_for('PetCare.login'))
	accountDao = AccountDao()
	postDao = PostDao()
	postId = accountDao.get_account_post(session['logged_in'].rstrip())
	if postId is not None:
		return redirect(url_for('PetCare.edit_post'))
	if request.method == 'GET':
		return render_template('create_post.html', error=None)
	postInfo = Entities.make_post_info(session['logged_in'].rstrip(), request)
	if not postInfo:
		return render_template('create_post.html', error="Required Informaion Missing")
	postId = postDao.add_post(postInfo)
	accountDao.update_account_post(session['logged_in'].rstrip(), postId)
	return redirect(url_for('PetCare.list_posts'))

@bp.route('/edit_post', methods=['GET', 'POST'])
def edit_post():
	if session.get('logged_in') is None:
		return redirect(url_for('PetCare.login'))
	accountDao = AccountDao()
	postDao = PostDao()	
	postId = accountDao.get_account_post(session['logged_in'].rstrip())
	
	if postId is None:
		return redirect(url_for('PetCare.create_post'))
	
	prevPost = postDao.get_post(postId)
	prevPostInfo = Entities.make_post_output(dict(prevPost))
	if request.method == 'GET':
		return render_template('edit_post.html', error=None, prevPost=prevPostInfo)

	prevPostDict = dict(prevPost)
	postInfo = Entities.make_post_info(session['logged_in'].rstrip(), request, prevPostDict)
	if not postInfo:
		return render_template('edit_post.html', error="Required Informaion Missing", prevPost=None)
	
	postInfo['id'] = postId
	postDao.update_post(postInfo)
	return redirect(url_for('PetCare.list_posts'))

@bp.route('/view_post', methods=['GET'])
def view_post():
	if session.get('logged_in') is None:
		return redirect(url_for('PetCare.login'))
	postDao = PostDao()
	post = postDao.get_post(request.args['postId'])
	status = 'PENDING'
	if post['match'] is not None and len(post['match']) > 0:
		status = 'MATCHED'
	if time.time() > post['end_date']:
		status = 'FINISHED'
	postInfo = Entities.make_post_output(dict(post))
	isOwner = (session.get('logged_in') == post['owner_id'])
	accountDao = AccountDao()
	ownername =  accountDao.get_name(post['owner_id'])
	return render_template('view_post.html', post=postInfo, status=status, isOwner=isOwner, owner=ownername)

@bp.route('/delete_post', methods=['POST'])
def delete_post():
	if session.get('logged_in') is None:
		return redirect(url_for('PetCare.login'))
	accountDao = AccountDao()
	ownerMatched = accountDao.remove_account_post(session['logged_in'].rstrip(), request.form['postId'])
	if not ownerMatched:
		return redirect(url_for('PetCare.list_posts'))
	postDao = PostDao()
	prevImages = postDao.remove_post(request.form['postId'])
	for img in prevImages:
		ImageHandler.delete_image(img)
	return redirect(url_for('PetCare.list_posts'))

@bp.route('/interest_post', methods=['POST'])
def interest_post():
	if session.get('logged_in') is None:
		return redirect(url_for('PetCare.login'))
	accountDao = AccountDao()
	postDao = PostDao()
	postOwnerId = postDao.add_interest(request.form['postId'], session['logged_in'].rstrip())
	if postOwnerId:
		postOwnerEmail = accountDao.get_account_email(postOwnerId)
		userEmail = accountDao.get_account_email(session['logged_in'].rstrip())
		EmailHandler.send_interest(postOwnerId, postOwnerEmail, session['logged_in'].rstrip(), userEmail)
	return redirect(url_for('PetCare.list_posts'))

@bp.route('/prompt_login', methods=['GET', 'POST'])
def prompt_login():
	if request.method == 'GET':
		return render_template('prompt_login.html', userId=request.args['userId'].rstrip(), targetId=request.args['targetId'], error=None)
	accountDao = AccountDao()
	if not accountDao.check_account_id_password(request.form['userId'], request.form['password']):
		return render_template('prompt_login.html', userId=request.form['userId'], targetId=request.form['targetId'], error="Wrong Password")
	session['logged_in'] = request.form['userId']
	return redirect(url_for('PetCare.profile', userId=request.form['targetId']))

@bp.route('/match', methods=['POST'])
def match():
	if session.get('logged_in') is None:
		return redirect(url_for('PetCare.login'))
	accountDao = AccountDao()
	postId = accountDao.get_account_post(session['logged_in'].rstrip())
	if postId is not None:
		postDao = PostDao()
		if postDao.add_match(postId, request.form['userId']):

PetCare/templates/list_posts.html
{% extends "layout.html" %}
{% block body %}
    <head>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script type=text/javascript>
            $(function() {
              $('a#load_more_button').bind('click', function() {
                $.getJSON('/_load_more_posts', {
                  offset: $('div.postCell').length,
                }, function(data) {
                  console.log(data)

                  if (data.length < 4) {
                    var readMoreButton = document.getElementById('read-more');
                    readMoreButton.style.display = 'none'; 
                  }

                  var containerDiv = document.getElementById('allPosts')

                  var rowDiv;
                  rowDiv = document.createElement('div')
                  rowDiv.className = 'row'       
     
                  for (i = 0; i < data.length; i++) {
                    post = data[i]

                    var cellA = document.createElement('a')
                    cellA.href = '{{ url_for('PetCare.view_post')}}'.concat('?postId=').concat(post.id)

                    var span3Div = document.createElement('div')
                    span3Div.className = 'span3 postCell'
                    
                    var homePostDiv = document.createElement('div')
                    homePostDiv.className = 'home-post' 
                    
                    var postImageDiv = document.createElement('div')
                    postImageDiv.className = 'post-image'
                    var postMetaDiv = document.createElement('div')
                    postMetaDiv.className = 'post-meta'
                    var entryContentDiv = document.createElement('div')
                    entryContentDiv.className = 'entry-content'

                    var maxImgImg = document.createElement('img')
                    maxImgImg.className = 'max-img'
                    maxImgImg.src = post.image1

                    var iconCalendarI = document.createElement('i')
                    iconCalendarI.className = 'icon-calendar icon-2x'
                    var dateSpan1 = document.createElement('span')
                    dateSpan1.className = 'date'
                    dateSpan1.innerHTML = post.start_date.concat('-')
                    var dateSpan2 = document.createElement('span')
                    dateSpan2.className = 'date'
                    dateSpan2.innerHTML = post.end_date
                    
                    var h5 = document.createElement('h5')
                    var strong = document.createElement('strong')
                    var jinhaoA = document.createElement('a')
                    jinhaoA.href = '#'
                    jinhaoA.innerHTML = post.name
                    var p = document.createElement('p')
                    p.innerHTML = post.notes.substr(0, 100) + "..."
                    
                    rowDiv.appendChild(cellA)
                    cellA.appendChild(span3Div)
                    span3Div.appendChild(homePostDiv)                                      
                    
                    homePostDiv.appendChild(postImageDiv)
                    homePostDiv.appendChild(postMetaDiv)
                    homePostDiv.appendChild(entryContentDiv)          

                    postImageDiv.appendChild(maxImgImg)
                    postMetaDiv.appendChild(iconCalendarI)
                    postMetaDiv.appendChild(dateSpan1)
                    postMetaDiv.appendChild(dateSpan2)
                    entryContentDiv.appendChild(h5)
                    entryContentDiv.appendChild(p)

                    h5.appendChild(strong)
                    strong.appendChild(jinhaoA)

                    if (i % 4 == 3 || i == data.length - 1) {
                        containerDiv.appendChild(rowDiv)                                                
                        rowDiv = document.createElement('div')
                        rowDiv.className = 'row'       
                    }
                  }
                });
                return false;
              });
            });
        </script>
    </head>

    <form action="{{ url_for('PetCare.filter_posts') }}" enctype="multipart/form-data" method=post>
        <div class="container" style="margin-top: 2%">
            <div class="row" >
                <div class="span2">
                    <label for="Gender">Gender</label>
                    <select name="gender" id="gender-filter" style="width: 130px"/>
                        <option value=-1 >no filter</option>
                        <option value=1 >Male</option>
                        <option value=0 >Female</option>
                    </select>
                </div>
                <div class="span2">
                    <label for="Species">Species</label>
                    <select name="species" id="species-filter" style="width: 130px"/>
                        <option value="">no filter</option>
                        <option value="Dog">Dog</option>
                        <option value="Cat">Cat</option>
                        <option value="Bird">Bird</option>
                    </select>
                </div>
                <div class="span2">
                    <label for="Age">Age</label>
                    <select name="age" id="age-filter" style="width: 130px"/>
                        <option value=-1>no filter</option>
                        <option value=0 > < 1 year</option>
                        <option value=1 >1 year</option>
                        <option value=2 >2 year</option>
                        <option value=3 >3 year</option>
                        <option value=4 >4 year</option>
                        <option value=5 >5 year</option>
                        <option value=6 >6 year</option>
                        <option value=7 >7 year</option>
                        <option value=8 >8 year</option>
                        <option value=9 >9 year</option>
                        <option value=10 > >= 10 year</option>
                    </select>
                </div>
                <div class="span2">
                    <label for="Start_Date">Earliest Start Date</label>
                    <input type=date name="start_date" value='' style="width: 130px">
                </div>
                <div class="span2">
                    <label for="End_Date">Latest End Date</label>
                    <input type=date name="end_date" value='' style="width: 130px">
                </div>                
                <div class="span2">
                    <input value="filter" type="submit" class="btn btn-primary btn-large btn-rounded" style="width: 150px; margin-top: 4%">
                </div>
            </div>
        </div>
    </form>
    
    <section id="blog" class="section">
		<div class="container" id="allPosts">
        {% for post_row in posts | batch(4, '&nbsp;') %}
            <div class="row">
            {% set outer_loop = loop %}
            {% for post in post_row %}
            {% if (outer_loop.index - 1) * 4 + loop.index <= posts|length %}
                <a href="{{ url_for('PetCare.view_post') + '?postId=' + post.id|string }}">
                    <div class="span3 postCell">
                        <div class="home-post">
                            <div class="post-image">
                                <img class="max-img" src="{{post.image1}}" />
                            </div>
                            <div class="post-meta">
                                <i class="icon-calendar icon-2x"></i>
                                <span class="date">{{post.start_date|string}}-</span>
                                <span class="date">{{post.end_date|string}}</span>
                            </div>
                            <div class="entry-content">
                                <h5><strong><a href="#">{{ post.name }}</a></strong></h5>
                                <p>
                                    {{ post.notes[:100] + '...' }} 
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
            {% endif %}
            {% endfor %}
            </div>
        {% endfor %}
		</div>

        <div class="blankdivider30"></div>
        {% if posts|length > 0 and not fromFilter%}
        <div class="aligncenter" id="read-more">
            <a href="#" id=load_more_button class="btn btn-large btn-theme">More blog post</a>
        </div>
        {% endif %}
	</section>
{% endblock %}

PetCare/templates/login.html
{% extends "layout.html" %}
{% block body %}

  <div class="logo" style="width: 300px; margin-left: 40%; margin-top: 3%">
    <img src="../static/Maxim/img/loginHead2.png" alt="" />
  </div>
  
  <form action="{{ url_for('PetCare.login') }}" method=post>
    <dl>
      <dt style="width: 200px; margin-left: 43%; margin-top: 2%">Username:
      <dd><input type=text name=email style="width: 200px; margin-left: 42.5%">
      <dt style="width: 200px; margin-left: 43%">Password:
      <dd><input type=password name=password style="width: 200px; margin-left: 42.5%">
      <dt><input class="btn btn-large btn-theme" type=submit value=Login style="width: 200px; margin-left: 43.5%; margin-top: 2%">
    </dl>
  </form>

  
  <a class="btn btn-large btn-theme" style="width: 150px; height: 23px; margin-left: 43.5%; margin-bottom: 1%;" href="{{ url_for('PetCare.register') }}">Register</a>

  <center>{% if error %}<p class=error><strong>Reminder:</strong> {{ error }}{% endif %}</center>

  <div class="logo" style="width: 600px; margin-left: 62%; margin-top: -14%; margin-bottom: 8%">
    <img src="../static/Maxim/img/doghomepage.gif" alt="" />
  </div>


{% endblock %}  

PetCare/templates/profile.html
{% extends "layout.html" %}
{% block body %}
<head>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <style>
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      div.stars {
        width: 270px;
        display: inline-block;
      }
      input.star { display: none; }
      label.star {
        float: right;
        padding: 10px;
        font-size: 36px;
        color: #444;
        transition: all .2s;
      }
      input.star:checked ~ label.star:before {
        content: '\f005';
        color: #FD4;
        transition: all .25s;
      }
      input.star-5:checked ~ label.star:before {
        color: #FE7;
        text-shadow: 0 0 20px #952;
      }
      input.star-1:checked ~ label.star:before { color: #F62; }
      label.star:hover { transform: rotate(-15deg) scale(1.3); }
      label.star:before {
        content: '\f006';
        font-family: FontAwesome;
      }
    </style>
</head>

  <section class="spacer green">
    <div class="container">
      <div class="row">
        <div class="span12 aligncenter flyUp">
          <h2 class="pagetitle">{{account.name}}
        </div>
      </div>
    </div>
  </section>
  
  <!-- section: team -->
  <section id="maincontent" class="inner">
    <div class="container">
      <div class="row">

        <div class="span6">
          <h4>Main Information</h4>
          <!-- start: Accordion -->
          <div class="accordion" id="accordion2">
            <div class="accordion-group">
              <div class="accordion-heading">
                <a class="accordion-toggle active">Public Information</a>
              </div>
              <div id="collapseOne" class="accordion-body collapse in">
                <div class="accordion-inner">
                  <p>
                    Account Id: {{ account.id }}
                  </p>
                  <p>
                    Name: {{ account.name }}
                  </p>
                  <p>
                    Gender: {{ 'Male' if account.gender==1 else 'Female' }}
                  </p>
                  <p>
                    Age: {{ account.age }}
                  </p>
                  <p>
                    Departement: {{ account.department }}
                  </p>
                  <p>
                    College: {{ account.college }}
                  </p>
                  <p>
                    Reputation: {{ account.reputation_sum / account.reputation_num }}
                  </p>
                </div>
              </div>
            </div>
            {% if session.logged_in == account.id %}
              <div class="accordion-group">
                <div class="accordion-heading">
                  <a class="accordion-toggle active">Private Information</a>
                </div>
                <div id="collapseTwo" class="accordion-body collapse in">
                  <div class="accordion-inner">
                    <p>
                      Email: {{ account.email + "@ucsd.edu" }}
                    </p>
                    <p>
                      Reputation: {{ account.reputation_sum / account.reputation_num }}
                    </p>
                  </div>
                </div>
              </div>
            {% endif %}
          </div>
          <!--end: Accordion -->
        </div>

        <div class="span6">
          <h4>Post History</h4>
          {% if posts|length == 0 %}
            <h4>This user has not posted anything yet.</h4>
          {% else %}
            <div class="tabbable">
              <ul class="nav nav-tabs">
                <li class="active"><a href="#post1" data-toggle="tab">1</a></li>
                {% for i in range(2,posts|length+1) %}
                  <li><a href={{"#post"+i|string}} data-toggle="tab">{{i}}</a></li>
                {% endfor %}
              </ul>
              <div class="tab-content">
                {% for i in range(1,posts|length+1) %}
                  <div class="tab-pane active" id={{"post"+i|string}}>
                    <a href="{{ url_for('PetCare.view_post')~'?postId='~posts[i - 1].id }}">
                      <img src="{{ posts[i-1].image1 }}" alt="Mountain View">
                    </a>
                  </div>
                {% endfor %}
              </div>
            </div>
          {% endif %}
        </div>
      </div>
      {# image with url #}
      {% if status == 'INTERESTED' %}
        <div class="row">
          <div class="span12">
            <div class="span3">
              <form action="{{ url_for('PetCare.match') }}" method=post>
                <input type=hidden name=userId value={{ request.args['userId'] }}>
                <input type=submit value=Approve class="btn btn-primary btn-large btn-rounded" style="width:250px;">
              </form>
            </div>
          </div>
        </div> 
      {% endif %}
      {% if status[:7] == 'MATCHED' %}
        <div class="row">
          <div class="span12">
            <div class="span3">
              <form action="{{ url_for('PetCare.review') }}" method=post>
                <div class="stars" style="width: 300px; margin-left: 32%">
                  {% for i in [5, 4, 3, 2, 1] %}
                    {% if i|string == status[7] %}
                      <input class={{"star star-"+i|string}} id={{"star-"+i|string}} type=radio name=review value={{i}} checked />
                    {% else %}
                      <input class={{"star star-"+i|string}} id={{"star-"+i|string}} type=radio name=review value={{i}} />
                    {% endif %}
                    <label class={{"star star-"+i|string}} for={{"star-"+i|string}}></label>
                  {% endfor %}
                </div>
                <input class="btn btn-large btn-theme" type=submit value="Submit Review" style="width: 300px; margin-left: 38%; margin-top: 2%">
              </form>
            </div>
          </div>
        </div> 
      {% endif %}

    </div>
    <!-- end container -->
  </section>

{% endblock %}

PetCare/templates/view_post.html
{% extends "layout.html" %}
{% block body %}
	<!-- spacer section -->
	<section class="spacer green">
		<div class="container">
			<div class="row">
				<div class="span12 aligncenter flyUp">
					<h2 class="pagetitle">{{post.name}}
				</div>
			</div>
		</div>
	</section>
	<!-- end spacer section -->
	<!-- section: team -->
	<section id="maincontent" class="inner">
		<div class="container">
			<div class="row">

				<div class="span6">
					<h4>Main Information</h4>
					<!-- start: Accordion -->
					<div class="accordion" id="accordion2">
						<div class="accordion-group">
							<div class="accordion-heading">
								<a class="accordion-toggle active" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
								<i class="icon-minus"></i> Pet Information </a>
							</div>
							<div id="collapseOne" class="accordion-body collapse in">
								<div class="accordion-inner">
									<p>
										Name: {{post.name}}
									</p>
									<p>
										Gender: {{post.gender}}
									</p>
									<p>
										Species (and Breed): {{ post.species + (' (' + post.breed + ')') if post.breed }}
									</p>
									<p>
										Age: {{post.age}}
									</p>
									<p>									
										Vaccination: {{post.vaccination}}
									</p>
								</div>
							</div>
						</div>
						<div class="accordion-group">
							<div class="accordion-heading">
								<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
								<i class="icon-plus"></i> Owner </a>
							</div>
							<div id="collapseThree" class="accordion-body collapse">
								<div class="accordion-inner">
									<a href="{{ url_for('PetCare.profile')~'?login='~session.logged_in~'&userId='~post.owner_id }}">
										Name: {{owner}}
									</a>
								</div>
							</div>
						</div>
						<div class="accordion-group">
							<div class="accordion-heading">
								<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
								<i class="icon-plus"></i> Post Information </a>
							</div>
							<div id="collapseFour" class="accordion-body collapse">
								<div class="accordion-inner">
									<p>
										Start Date: {{post.start_date}}
									</p>
									<p>
										End Date: {{post.end_date}}
									</p>
									<p>
										Post Date: {{post.post_date}}
									</p>
									<p>
										Notes: {{post.notes}}
									</p>
								</div>
							</div>
						</div>
					</div>
					<!--end: Accordion -->
				</div>


				<div class="span6">
					<h4>Pictures</h4>
					<div class="tabbable">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#one" data-toggle="tab">1</a></li>
							<li><a href="#two" data-toggle="tab">2</a></li>
							<li><a href="#three" data-toggle="tab">3</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="one">
								<img src="{{ post.image1 }}" alt="Mountain View">
							</div>
							<div class="tab-pane" id="two">
								<img src="{{ post.image2 }}" alt="Mountain View">
							</div>
							<div class="tab-pane" id="three">
								<img src="{{ post.image3 }}" alt="Mountain View">
							</div>
						</div>
					</div>
				</div>

				
			</div>

			{% if status == 'PENDING' %}
				{% if isOwner %}
				<div class="row">
					<div class="span3">
						<a href="{{ url_for('PetCare.edit_post') }}" class="btn btn-primary btn-large btn-rounded" style="width: 150px;">Edit</a>
					</div>
					<div class="span3">
						<form action="{{ url_for('PetCare.delete_post') }}" enctype="multipart/form-data" method=post>
							<input type=hidden name=postId value={{ post.id }}>
							<input type=submit value=Delete class="btn btn-primary btn-large btn-rounded" style="width:200px; background-color: red">
						</form>
					</div>
				</div>
				{% else %}
				<div class="row">
					<div class="span12">
						<div class="span3">
						<form action="{{ url_for('PetCare.interest_post') }}" enctype="multipart/form-data" method=post>
							<input type=hidden name=postId value={{ post.id }}>
							<input type=submit value="I'm interested!" class="btn btn-primary btn-large btn-rounded" style="width:250px;">
						</form>
					</div>
					</div>
				</div>			
				{% endif %}
			{% endif %}
		</div>
		<!-- end container -->
	</section>
{% endblock %}